### ISSUE TITLE
Add new code example

### ISSUE THREAD

**Issue by lucifertrj** [skops-dev/skops#177] opened 2022-10-08 07:51 UTC
I would love to contribute to a new code example on `tabular-regression`. If not you can even assign any regression-based example to me. 
Thanks

**Comment by adrinjalali** [comment] 2022-10-10 12:32
Duplicate of https://github.com/skops-dev/skops/issues/117. Feel free to take a task from that issue.

**Closed by adrinjalali** 2022-10-10 12:32 UTC
